openapi: 3.0.0
info:
  version: 0.0.1
  title: ticketBook API Specification
  x-unofficialSpec: false
  x-nullable: true
servers:
  - url: 'https://localhost:8080/{basePath}'
    description: DEV
    variables:
      basePath:
        default: api/v1
x-tagGroups:
  - name: API
    tags:
      - attendee
      - event
      - ticket
      - order
      - payment
tags:
  - name: attendee
    x-displayName: Attendee API
  - name: event
    x-displayName: Event API
  - name: ticket
    x-displayName: Ticket API
  - name: order
    x-displayName: Order API
  - name: payment
    x-displayName: Payment API
paths:
  '/attendee/{id}':
    get:
      tags:
        - attendee
      summary: Get attendee by id
      description: ''
      operationId: get_attendee
      responses:
        '200':
          description: Success
